import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Moon,
  PencilIcon,
  MoreVertical,
  Pizza,
  Plus,
  UserCogIcon,
  Settings,
  SunMedium,
  Trash,
  UserCircleIcon,
  X,
  Search,
  PhoneIcon,
  MailIcon,
  BookOpenText,
  Copy,
  LucideIcon,
  Monitor,
  Download,
  Github,
  ChevronsUpDown,
  MoreHorizontal,
  EditIcon,
  ArchiveRestore,
  TrashIcon,
  ArrowDown,
  RefreshCw,
  Share,
  XCircle,
  CornerDownLeft,
  SlashIcon,
  PanelLeft,
  PanelRight,
  Share2,
} from "lucide-react";

import {
  AiFillFilePdf,
  AiFillWechat,
  AiFillDatabase,
  AiFillQuestionCircle,
  AiFillBell,
  AiFillMobile,
} from "react-icons/ai";

import { GoSignOut } from "react-icons/go";

import { TiTick } from "react-icons/ti";

export type Icon = LucideIcon;

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: UserCircleIcon,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  search: Search,
  gitHub: Github,
  twitter: X,
  check: Check,
  orderbook: BookOpenText,
  pdf: AiFillFilePdf,
  chat: AiFillWechat,
  storage: AiFillDatabase,
  questions: AiFillQuestionCircle,
  notifications: AiFillBell,
  mobile: AiFillMobile,
  chevronsUpDown: ChevronsUpDown,
  phone: PhoneIcon,
  mail: MailIcon,
  pencil: PencilIcon,
  student: PencilIcon,
  teacher: UserCogIcon,
  monitor: Monitor,
  moreHorizontal: MoreHorizontal,
  editClassroom: EditIcon,
  archiveClassroom: ArchiveRestore,
  deleteClassroom: TrashIcon,
  download: Download,
  copy: Copy,
  arrowDown: ArrowDown,
  refresh: RefreshCw,
  share: Share,
  stop: XCircle,
  enter: CornerDownLeft,
  slash: SlashIcon,
  panelLeft: PanelLeft,
  panelRight: PanelRight,
  leaveClassroom: GoSignOut,
  shareClassroom: Share2,
  shareClassroomTaked: TiTick,
};
