import {
  AlertTriangle,
  ArchiveRestore,
  ArrowDown,
  ArrowDownToLine,
  ArrowRight,
  ArrowUpDown,
  BookOpenText,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  ChevronUp,
  Command,
  Copy,
  CornerDownLeft,
  CreditCard,
  Download,
  EditIcon,
  ExternalLink,
  Eye,
  File,
  FileText,
  Github,
  Heart,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  LucideIcon,
  MailIcon,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  PanelLeft,
  PanelRight,
  Paperclip,
  PencilIcon,
  PhoneIcon,
  Pizza,
  Plus,
  RefreshCw,
  Reply,
  RotateCcw,
  RotateCw,
  Search,
  Settings,
  Share,
  Share2,
  SlashIcon,
  SunMedium,
  ThumbsDown,
  ThumbsUp,
  Trash,
  TrashIcon,
  Upload,
  UserCircleIcon,
  UserCogIcon,
  X,
  XCircle,
} from "lucide-react"
import {
  AiFillBell,
  AiFillDatabase,
  AiFillFilePdf,
  AiFillMobile,
  AiFillQuestionCircle,
  AiFillWechat,
} from "react-icons/ai"
import { FaRegLightbulb, FaSurprise } from "react-icons/fa"
import { FaHandsClapping } from "react-icons/fa6"
import { GoSignOut } from "react-icons/go"
import { TiTick } from "react-icons/ti"

export type Icon = LucideIcon

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: UserCircleIcon,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  search: Search,
  gitHub: Github,
  twitter: X,
  check: Check,
  orderbook: BookOpenText,
  pdf: AiFillFilePdf,
  chat: AiFillWechat,
  storage: AiFillDatabase,
  questions: AiFillQuestionCircle,
  notifications: AiFillBell,
  mobile: AiFillMobile,
  chevronsUpDown: ChevronsUpDown,
  phone: PhoneIcon,
  mail: MailIcon,
  pencil: PencilIcon,
  student: PencilIcon,
  teacher: UserCogIcon,
  monitor: Monitor,
  moreHorizontal: MoreHorizontal,
  editClassroom: EditIcon,
  archiveClassroom: ArchiveRestore,
  deleteClassroom: TrashIcon,
  download: Download,
  copy: Copy,
  arrowDown: ArrowDown,
  ArrowUpDown: ArrowUpDown,
  refresh: RefreshCw,
  share: Share,
  stop: XCircle,
  enter: CornerDownLeft,
  slash: SlashIcon,
  panelLeft: PanelLeft,
  panelRight: PanelRight,
  leaveClassroom: GoSignOut,
  shareClassroom: Share2,
  shareClassroomTaked: TiTick,
  watchFile: Eye,
  downloadFile: ArrowDownToLine,
  replyComment: Reply,
  reactionLike: ThumbsUp,
  reactionDislike: ThumbsDown,
  reactionLove: Heart,
  reactionApplause: FaHandsClapping,
  reactionWow: FaSurprise,
  reactionInsightul: FaRegLightbulb,
  upload: Upload,
  paperclip: Paperclip,
  down: ChevronDown,
  up: ChevronUp,
  rotateCw: RotateCw,
  rotateCcw: RotateCcw,
  external: ExternalLink,
}
