import "@styles/globals.css";

import { GeistSans } from "geist/font";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Undrstnd | Give Your Documents Intelligence.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>{children}</body>
    </html>
  );
}
