import "@styles/globals.css";

import type { Metadata } from "next";
import { GeistSans } from "geist/font";

export const metadata: Metadata = {
  title: "Authentification | Undrstnd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>{children}</body>
    </html>
  );
}
