import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Undrstnd | Give Your Documents Intelligence.",
  description: "Generated by create next app",
};

import Header from "@/components/sections/navigation/Header";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
